name: EjerciciosJavaMinecraft
main: es.techtalents.main.Main
version: 1.0.0
commands:
   ejercicio1:
   ejercicio2:
   ejercicio3:
   ejercicio4:
   ejercicio5:
   ejercicio6:
   ejercicio7:
   ejercicio8:
   ejercicio9:
   ejercicio10:
   ejercicio1m: